name: random-reviewer
on:
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      SECRET_GITHUB_TOKEN:
        default: asdasd

jobs:
  random-reviewer:
    runs-on: ubuntu-latest

    steps:
      # chckout
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache node modules
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo 'npm cache existed'
          npm ci
      #
      - name: run random reviewer
        env:
          SECRET_GITHUB_TOKEN: ${{secrets.SECRET_GITHUB_TOKEN}}
        run: npm run reviewer
