name: random-reviewer
on: workflow_dispatch
jobs:
  random-reviewer:
    runs-on: ubuntu-latest

    steps:
      # chckout
      - uses: actions/checkout@v3
      #
      - name: run random reviewer
        run: npm run reviewer
